import Head from 'next/head'
import {BsFillMoonStarsFill, BsTelegram} from 'react-icons/bs'
import {AiFillInstagram} from 'react-icons/ai'
import {IoLogoWhatsapp} from 'react-icons/io'
import Image from 'next/image'
import myPhoto from '../public/assets/media/photos/me.jpg'
import dinnerPromo from '../public/assets/media/img/potrfolioExmpls/eat.jpg'
import runPromo from '../public/assets/media/img/potrfolioExmpls/zabeg.jpg'
import cafeAd from '../public/assets/media/img/potrfolioExmpls/cafe-ad.jpg'
import roomPromo from '../public/assets/media/img/potrfolioExmpls/room-promo.jpg'
import salesAd from '../public/assets/media/img/potrfolioExmpls/sales-ad.jpg'
import investProjects from '../public/assets/media/img/potrfolioExmpls/invest-projects.jpg'
import diamondLikeThingy from '../public/assets/media/img/fieldsIllustrations/diamond-like-thingy.png'
import cubeThingy from '../public/assets/media/img/fieldsIllustrations/cube-thingy.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Tailwind Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-5 min-w-fit md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb12 flex justify-between'>
            <h1 className='text-md font-burtons md:text-xl dark:text-white'>developedbyalexflowers</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill 
                  className='crusor-pointer text-2xl dark:fill-white'
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-4 md:ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Alex Flowers</h2>
            <h3 className='text-2xl py- 2 md:text-3xl dark:text-white'>Developer & designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400'>Freelancer providing services for programming and design content needs. Join me down below and let's get some work done!</p>
          </div>  
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <BsTelegram className='cursor-pointer'/>
            <AiFillInstagram className='cursor-pointer'/>
            <IoLogoWhatsapp className='cursor-pointer'/>
          </div>
          <div className='relative rounded-full overflow-hidden flex justify-center w-80 h-80 mt-20 mx-auto md:h-96 md:w-96'>
            <Image src={myPhoto} layout="fill" objectFit="cover"/>
          </div>
        </section>
        <section>
          <div className='mt-8 md:max-w-md md:mx-auto'>
            <h3 className="text-3xl py-1 md:text-center dark:text-teal-600">Services I offer</h3>
            <p className='text-md py-2 leading-8 md:text-center dark:text-white'>
              if you want a frontend side of your website to be well-made, fast-loading for clients, 
              interactive, adaptive for mobile, tablets and screens, as well as to be set and ready for any future updates, 
              contact me, so you can have it done fast and in high quality!
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:shadow-teal-600'>
              <Image src={diamondLikeThingy} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-teal-600">Beautiful Designs</h3>
              <p className="py-2 dark:text-white">Creating elegant designs suited for your company</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-400">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-400">Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-gray-400">Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:shadow-teal-600'>
              <Image src={cubeThingy} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-teal-600">Awesome Sites</h3>
              <p className="py-2 dark:text-white">Coding Beautiful Designs bringing them to life on your site</p>
              <h4 className="py-4 text-teal-600">Coding tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-400">React JS</p>
              <p className="text-gray-800 py-1 dark:text-gray-400">Tailwind CSS</p>
              <p className="text-gray-800 py-1 dark:text-gray-400">Webpack</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-600">Portfolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>Freelancer providing services for programming and design content needs. Join me down below and let's get some work done!</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className='basis-1/3 flex-1'>
              <Image 
                src={dinnerPromo} 
                className="rounded-lg object-cover" 
                width={'100%'} 
                height={'100%'} 
                layout="responsive"
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                src={runPromo} 
                className="rounded-lg object-cover" 
                width={'100%'} 
                height={'100%'} 
                layout="responsive"
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                src={salesAd} 
                className="rounded-lg object-cover" 
                width={'100%'} 
                height={'100%'} 
                layout="responsive"
              />  
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                src={roomPromo} 
                className="rounded-lg object-cover" 
                width={'100%'} 
                height={'100%'} 
                layout="responsive"
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                src={cafeAd} 
                className="rounded-lg object-cover" 
                width={'100%'} 
                height={'100%'} 
                layout="responsive"
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                src={investProjects} 
                className="rounded-lg object-cover" 
                width={'100%'} 
                height={'100%'} 
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
